services:
  - type: web
    name: restroflow-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://restroflow-j6ru.onrender.com